Repository DazzlingFugu/ember-fr-guides-source, pull requests merged in 2024-02, with the labels that each got.

#233 Refine our `pre-commit` git hook
  .githooks/pre-commit
  package.json
  scripts/preinstall.mjs
Labels: enhancement

#223 Translate `guides/configuring-ember/build-targets.md` to French
  .local.dic
  .remarkignore
  guides/configuring-ember/build-targets.md
Labels: Guides FR trad

#241 feat: create a script to sort `.local.dic` file
  .local.dic
  CONTRIBUTING.md
  package.json
  scripts/lint:fix:local-dic.mjs
Labels: enhancement

#238 Translate guides/applications/initializers.md
  .remarkignore
  guides/applications/initializers.md
Labels: Guides FR trad

#240 build: update versions of node and npm for Volta
  package-lock.json
  package.json
Labels: dependencies
